-- Auto-generated SQL transformation script
-- Generated by Migrion Schema Mapper

INSERT INTO target_table (
  name,
  email,
  phone,
  create_date,
  active,
  customer_rank,
  total_invoiced,
  street,
  city,
  zip
)
SELECT
  customer_name,
  email_address,
  phone_num,
  registration_date,
  account_status == 'active' ? true : false -- account_status,
  total_purchases,
  lifetime_value,
  street_address,
  city_name,
  zip_code
FROM source_table;