[theme]
primaryColor="#2E5EAA"
backgroundColor="#0E1117"
secondaryBackgroundColor="#1C2333"
textColor="#FAFAFA"
font="sans serif"

[server]
headless = true
port = 8501
enableXsrfProtection = false

[browser]
gatherUsageStats = false
